services:
  redroid:
    image: proteomesh:latest
    container_name: redroid-clean
    privileged: true
    restart: unless-stopped
    cpuset: "0-7"
    mem_limit: 2560m
    mem_reservation: 1536m
    ports:
      - "5580:5555"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    volumes:
      - ./data-clean:/data
      - ./profiles/presets/pixel5_redfin.json:/system/etc/proteomesh_profile.json:ro
    command:
      - androidboot.redroid_gpu_mode=guest
      - androidboot.use_redroid_c2=1
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=2340
      - androidboot.redroid_dpi=440
      - androidboot.redroid_fps=90

  redroid-s21:
    image: proteomesh:latest
    container_name: redroid-s21
    privileged: true
    restart: unless-stopped
    cpuset: "0-7"
    mem_limit: 2560m
    mem_reservation: 1536m
    ports:
      - "5582:5555"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    volumes:
      - ./data-s21:/data
      - ./profiles/presets/samsung_s21.json:/system/etc/proteomesh_profile.json:ro
    command:
      - androidboot.redroid_gpu_mode=guest
      - androidboot.use_redroid_c2=1
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=2400
      - androidboot.redroid_dpi=421
      - androidboot.redroid_fps=120
