services:
  redroid:
    image: redroid/redroid:13.0.0_mindthegapps_magisk_widevine
    container_name: redroid-clean
    privileged: true
    restart: unless-stopped
    cpuset: "0-7"
    mem_limit: 2560m
    mem_reservation: 1536m
    ports:
      - "5580:5555"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    volumes:
      - ./data-clean:/data
      - ./bin/resetprop:/system/bin/resetprop:ro
      - ./build_magisk/system/lib64/libpixel_hw.so:/system/lib64/libpixel_hw.so:ro
      - ./build_magisk/system/lib64/libcutils.so:/system/lib64/libcutils.so:ro
      - ./build_magisk/system/lib/libpixel_hw.so:/system/lib/libpixel_hw.so:ro
      - ./build_magisk/system/lib64/libfake_hw.so:/system/lib64/libfake_hw.so:ro
      - ./build_magisk/system/lib/libfake_hw.so:/system/lib/libfake_hw.so:ro
      - ./build_magisk/system/lib/libndk_translation.so:/system/lib/libndk_translation.so:ro
      - ./build_magisk/system/lib64/libzygisk.solibnb.so:/system/lib64/libzygisk.solibnb.so:ro
      - ./build_magisk/system/lib64/libzygisk.solibzygisk.solibnb.so:/system/lib64/libzygisk.solibzygisk.solibnb.so:ro
      - ./build_magisk/system/etc/init/hw/init.zygote64_32.rc:/system/etc/init/hw/init.zygote64_32.rc:ro
      - ./build_magisk/system/etc/init/bootanim.rc:/system/etc/init/bootanim.rc:ro
      - ./build_magisk/system/etc/init/magisk/stub.apk:/system/etc/init/magisk/stub.apk:ro
      - ./build_magisk/system/etc/init/magisk/magisk:/system/etc/init/magisk/magisk:ro
      - ./build_magisk/system/build.prop:/system/build.prop:ro
      - ./build_magisk/vendor/build.prop:/vendor/build.prop:ro
      - ./build_magisk/vendor/lib64/libreference-ril.so:/vendor/lib64/libreference-ril.so:ro
      - ./build_magisk/vendor/etc/permissions/handheld_core_hardware.xml:/vendor/etc/permissions/handheld_core_hardware.xml:ro
      - ./build_magisk/system/etc/init/integrity_props.rc:/system/etc/init/integrity_props.rc:ro
      - ./build_magisk/system/etc/init/mask_proc.rc:/system/etc/init/mask_proc.rc:ro
      - ./build_magisk/system/bin/apply-props.sh:/system/bin/apply-props.sh:ro
      - ./build_magisk/system/bin/mask-early.sh:/system/bin/mask-early.sh:ro
      - ./build_magisk/system/bin/manage-spoof:/system/bin/manage-spoof:ro
    command:
      - androidboot.redroid_gpu_mode=guest
      - androidboot.use_redroid_c2=1
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=2340
      - androidboot.redroid_dpi=440
      - androidboot.redroid_fps=90
